### ISSUE TITLE
Add draft-07 migration for ajv 6.0.0

### ISSUE THREAD

**Issue by joebowbeer** [epoberezkin/json-schema-migrate#1]

**Comment by epoberezkin** [comment]
Is it really necessary given that draft-07 is the same and only requires updating the reference to meta-schema from 06?

**Comment by joebowbeer** [comment]
I think it's confusing that ajv no longer supports draft-06 (by default), and this migration tool doesn't migrate to -07.

**Comment by epoberezkin** [comment]
As I said, the only difference is in $schema. I don’t mind the change that would update API (no need for draft6 in it, I don’t see any point in migrating to multiple drafts, this package should only migrate to the latest supported).
Optionally, the support for “switch” migration can be added, but I’m not sure if anybody needs it.
It will be a major version change.

**Comment by jscharett** [comment]
Any plans on supporting latest version, 2019-09?

**Comment by epoberezkin** [comment]
v1 of this package supports migration to draft-07 and to draft-2019-09
